name: "Setup conda"
description: "Install conda Miniconda or Anaconda."

inputs:
  conda_type:
    description: "Version of conda to install"
    required: true
    default: "Anaconda"

outputs:
  cache-path:
    description: "Path to the conda installer, e.g. for use with actions/cache."
    value: ${{ steps.install.outputs.cache-path }}

runs:
  using: "composite"
  steps:
  - name: Install conda
    id: install
    env:
      RUNNER_OS: ${{ runner.os }}
      CONDA_TYPE: ${{ inputs.version }}
      GHA_PATH: ${{ github.action_path }}
    run: ${GITHUB_ACTION_PATH}/script.sh
    shell: bash


  - name: Confirm conda is on PATH
    run: conda
    shell: bash
