name: "Setup conda"
description: "Install Anaconda or Miniconda"

inputs:
  installer:
    description: "Installer to use: one of anaconda, mambaforge, or miniconda"
    required: true
    default: "anaconda"
  version:
    description: "Version of installer to use"
    required: true
    default: "2021.11"

outputs:
  cache-path:
    description: "Path to the installer, e.g. for use with actions/cache."
    value: ${{ steps.install.outputs.cache-path }}
  cmd:
    description: "Executable name of the installed package manager: 'conda' or 'mamba'."
    value: ${{ steps.install.outputs.cmd }}

runs:
  using: composite
  steps:
  - name: Install conda
    id: install
    env:
      INSTALLER: ${{ inputs.installer }}
      VERSION: ${{ inputs.version }}
    run: ${GITHUB_ACTION_PATH}/script.sh
    shell: bash

  - name: Confirm installed package manager is on PATH
    run: ${{ steps.install.outputs.cmd }} info
    shell: bash
