name: Set up GAMS
description: Install the GAMS executable.

inputs:
  license:
    description: "Content for gamslice.txt, e.g. from a repo secret."
    require: false
    default: null
  version:
    description: "Version of GAMS to install"
    required: false
    default: "25.1.1"

runs:
  using: composite
  steps:
  - name: Identify cache paths
    id: path
    run: ${GITHUB_ACTION_PATH}/script.py pre ${{ inputs.version }}
    shell: bash

  - name: Restore cache, if any
    id: restore-cache
    uses: actions/cache/restore@v4
    with:
      path: |
        ${{ steps.path.outputs.dist }}
        ${{ steps.path.outputs.install }}
        !${{ steps.path.outputs.install }}/gamslice.txt
      key: setup-gams-${{ runner.os }}-${{ runner.arch }}-${{ inputs.version }}

  - name: Set up GAMS
    env:
      GAMS_LICENSE: ${{ inputs.license }}
    run: |
      echo "GAMS_LICENSE=${{ env.GAMS_LICENSE }}" >> $GITHUB_ENV
      ${GITHUB_ACTION_PATH}/script.py install ${{ inputs.version }}
    shell: bash

  # - name: Show contents of working directory
  #   run: ls -lR
  #   shell: bash

  - name: Cache GAMS distribution and installed files
    if: "! ${{ steps.restore-cache.outputs.cache-hit }}"
    uses: actions/cache/save@v4
    with:
      path: |
        ${{ steps.path.outputs.dist }}
        ${{ steps.path.outputs.install }}
        !${{ steps.path.outputs.install }}/gamslice.txt
      key: setup-gams-${{ runner.os }}-${{ runner.arch }}-${{ inputs.version }}
