# Verify that the setup-conda action works

name: Validate setup-conda action

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  conda:
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
        conda: [Anaconda, Miniconda]

    runs-on: ${{ matrix.os }}
    name: ${{ matrix.os }}-${{ matrix.conda }}

    steps:  
    - name: Setup conda
    - uses: iiasa/actions/setup-conda@main
      with:
        conda_type: ${{ matrix.conda }}
        
    - name: Check conda version
      run: conda --version

